## Multiple Linear Regression from Scratch using Python

### Multiple Linear Regression (MLR)

Multiple Linear Regression (MLR) is a statistical technique used to model the relationship between two or more predictor variables (also called independent variables) and a single response variable (also called dependent variable). It assumes that there is a linear relationship between the predictors and the response variable, meaning that a change in one of the predictor variables will result in a proportional change in the response variable

MLR is an extension of simple linear regression, which involves only one predictor variable. In MLR, there can be multiple predictor variables, each with its own coefficient that indicates the strength and direction of the relationship between that predictor and the response variable, while controlling for the other predictors. The goal of MLR is to identify the combination of predictor variables that best predicts the response variable.

In <b>data science</b> and <b>machine learning</b>, Multiple Linear Regression (MLR) is a supervised learning algorithm used for predictive modeling. It involves building a linear equation that represents the relationship between multiple predictor variables and a response variable, and then using that equation to make predictions for new data points.

MLR is a commonly used technique in machine learning because it is simple to implement and provides interpretable results. It is often used in applications such as sales forecasting, price prediction, and risk analysis.

In MLR, the coefficients of the predictor variables are estimated using a technique called ordinary least squares (OLS). The OLS method finds the coefficients that minimize the sum of the squared differences between the predicted values and the actual values of the response variable. The resulting linear equation can then be used to make predictions for new data points.

Like other machine learning algorithms, MLR requires careful data preparation, feature engineering, and model selection to ensure accurate and reliable predictions. It is also important to evaluate the performance of the MLR model using appropriate metrics such as mean squared error (MSE) or R-squared.

### Multiple Linear Regression (MLR) Mathematical Formulas 

#### Linear Equation for a Multilinear Regression 

The formula for the regression equation of the <b>least-squares regression</b> line for a <b>multiple linear regression</b> with $p$ independent variables is:

## $$y = b_0 + b_1 x_1 + b_2 x_2 + \cdots + b_p x_p$$

where $y$ is the dependent variable, $x_1, x_2, \dots, x_p$ are the independent variables, $b_0$ is the y-intercept, and $b_1, b_2, \dots, b_p$ are the coefficients of the independent variables.

#### Regression Coefficients / Model Coefficients / Regression Slope / Slope Coefficients

The formula for the <b>coefficients</b> of the least-squares regression line for a multiple linear regression is:

## $$\mathbf{b} = (\mathbf{X}^T \mathbf{X})^{-1} \mathbf{X}^T \mathbf{y}$$

where $\mathbf{b}$ is a vector of coefficients, $\mathbf{X}$ is the design matrix with dimensions $(n \times p+1)$, $\mathbf{y}$ is the vector of responses with dimensions $(n \times 1)$, and $(\mathbf{X}^T\mathbf{X})^{-1}$ is the inverse of the matrix $\mathbf{X}^T\mathbf{X}$.

<b>Note</b>: $n$ represents the number of observations or data points, and $p$ represents the number of predictor variables or features.
The design matrix $\mathbf{X}$ has dimensions $(n \times p+1)$ because it includes $n$ rows, one for each observation, and $p+1$ columns, one for each predictor variable and an additional column of 1s for the intercept term.
The response vector $\mathbf{y}$ has dimensions $(n \times 1)$ because it includes $n$ rows and one column, representing the response variable for each observation.

or

where $\mathbf{b}$ is a $p+1$ vector of the coefficients (including the intercept), $\mathbf{X}$ is a $n \times (p+1)$ matrix of the independent variables (including a column of 1's for the intercept), $\mathbf{y}$ is a $n$-dimensional vector of the dependent variable, and $(\mathbf{X}^T \mathbf{X})^{-1}$ is the inverse of the $p+1 \times p+1$ matrix $\mathbf{X}^T \mathbf{X}$.

#### Predicted / Fitted / Estimated / Regressor / Model values

The <b>predicted</b> values can be calculated as:

$$\mathbf{\hat{y}} = \mathbf{X}\mathbf{b}$$

where $\mathbf{\hat{y}}$ represents the vector of predicted values of the response variable. It is a column vector of size $n \times 1$, where $n$ is the number of observations in the dataset.

$\mathbf{X}$ represents the matrix of predictor variables. It is a matrix of size $n \times (p+1)$, where $p$ is the number of predictor variables. Each row of the matrix represents an observation, and each column represents a predictor variable.

$\mathbf{b}$ represents the vector of regression coefficients. It is a column vector of size $(p+1) \times 1$, where each element represents the regression coefficient for a specific predictor variable.

#### Residuals / Errors / Deviations / Noise / Residual Errors

The formula for the <b>residuals</b>, or <b>errors</b>, is:

$$\mathbf{e} = \mathbf{y} - \mathbf{X} \mathbf{b}$$ 
<center>or</center>
$$\mathbf{e} = \mathbf{y} - \mathbf{\hat{y}}$$

where $\mathbf{e}$ is an $n$-dimensional vector of the residuals. The residuals, which are the differences between the actual values and the predicted values.

#### Intercept / Constant term / Bias term

The intercept term, denoted by $b_0$, can be obtained as the first element of the vector $\mathbf{b}$, which is calculated using the formula:

$$\mathbf{b} = (\mathbf{X}^T \mathbf{X})^{-1} \mathbf{X}^T \mathbf{y}$$

where $\mathbf{y}$ is the vector of response variables. The first element of $\mathbf{b}$, denoted by $b_0$, is the estimated intercept term.

#### Total Sum of Squares (TSS)

The formula for the <b>total sum of squares (TSS)</b> is:

$$\text{TSS} = \sum_{i=1}^{n} (y_i - \overline{y})^2$$

where $n$ is the number of data points, $y_i$ is the $i$th value of the dependent variable, and $\overline{y}$ is the mean of the dependent variable.

#### Residual Sum of Squares (RSS)

The formula for the <b>residual sum of squares (RSS)</b> is:

$$\text{RSS} = \sum_{i=1}^{n} (y_i - \hat{y_i})^2$$

where $n$ is the number of data points, $y_i$ is the observed value of the dependent variable for the $i$th data point, and $\hat{y_i}$ is the predicted value of the dependent variable based on the least-squares regression line.

#### R-squared / Coefficient of determination / Proportion of explained variance / Goodness of fit

The formula for the <b>coefficient of determination</b>, or <b>R-squared</b>, is:

$$R^2 = 1 - \frac{\text{RSS}}{\text{TSS}}$$

where $\text{RSS}$ is the residual sum of squares, and $\text{TSS}$ is the total sum of squares.

R-squared (also known as the coefficient of determination) measures the proportion of the variance in the target variable that is explained by the model. It takes values between 0 and 1, with higher values indicating better model performance. An R-squared of 1 indicates that the model perfectly fits the data, while an R-squared of 0 indicates that the model provides no better predictions than the mean of the target variable.

#### Mean Absolute Error (MAE)

$$ MAE = \frac{1}{n} \sum_{i=1}^{n} \left| y_i - \hat{y_i} \right| $$

Mean Absolute Error (MAE) is a measure of the average absolute difference between the predictions and the true values. It takes into account the magnitude of the errors, but not their direction. MAE is easy to interpret, as it gives the average magnitude of the errors in the same units as the target variable.

#### Mean Squared Error (MSE)

$$ MSE = \frac{1}{n} \sum_{i=1}^{n} (y_i - \hat{y_i})^2 $$

Mean Squared Error (MSE) is similar to MAE, but it takes the square of the errors instead of their absolute value. This means that MSE gives more weight to large errors. MSE is also easy to interpret, but because it involves squaring the errors, it is more sensitive to outliers than MAE.

#### Root Mean Squared Error (RMSE)

$$ RMSE = \sqrt{\frac{1}{n} \sum_{i=1}^{n} (y_i - \hat{y_i})^2} $$

Root Mean Squared Error (RMSE) is simply the square root of MSE, and is often used as an alternative to MSE when we want the error metric to be in the same units as the target variable. RMSE also gives more weight to large errors, but its value is more interpretable than MSE because it is in the same units as the target variable.

<b>Note</b>: R-squared measures how well the model fits the data, while MAE, MSE, and RMSE measure the average difference between the predicted and actual values. MAE is less sensitive to outliers and easy to interpret, while MSE and RMSE give more weight to larger errors and are commonly used in optimization problems. RMSE is in the same units as the dependent variable and is therefore more interpretable than MSE.

R-squared, MAE, MSE, and RMSE are all metrics used to evaluate the performance of regression models in machine learning. Each metric provides a different aspect of the model's performance, and choosing the most appropriate one depends on the specific problem and requirements.

#### Linear Predictor Equation

The equation to <b>predict</b> the value of a dependent variable $y$ using a multiple linear regression model:

$$\hat{y} = b_0 + b_1x_1 + b_2x_2 + ... + b_px_p $$

where $\hat{y}$ is the predicted value of the response variable, $b_0$ is the intercept, $b_1$, $b_2$, ..., $b_p$ are the coefficients of the predictor variables $x_1$, $x_2$, ..., $x_p$, respectively.

### Multiple Linear Regression (MLR) Implementation

$y = b_0 + b_1 x_1 + b_2 x_2 + \cdots + b_p x_p$

$$\mathbf{b} = (\mathbf{X}^T \mathbf{X})^{-1} \mathbf{X}^T \mathbf{y}$$

The formula is the equation for the <b>Ordinary Least Squares (OLS)</b> estimator for the regression coefficients in a multiple linear regression model.

In more detail, let's break down each component of the formula:

- $\mathbf{X}$ is a matrix of predictor variables, with dimensions $n \times (p+1)$, where $n$ is the number of observations and $p$ is the number of predictors and an additional column of 1s for the intercept term.

- $\mathbf{y}$ is a vector of response variables, with length $n$.

- $\mathbf{X}^T$ is the transpose of the matrix $\mathbf{X}$, with dimensions $(p+1) \times n$.

- $\mathbf{X}^T \mathbf{X}$ is the matrix multiplication of the transpose of $\mathbf{X}$ and $\mathbf{X}$, with dimensions $(p+1) \times (p+1)$.

- $(\mathbf{X}^T \mathbf{X})^{-1}$ is the inverse of the matrix $\mathbf{X}^T \mathbf{X}$, if it exists. The inverse matrix is used to find the OLS estimate of the regression coefficients.

- $\mathbf{X}^T \mathbf{y}$ is the matrix multiplication of the transpose of $\mathbf{X}$ and $\mathbf{y}$, with dimensions $(p+1) \times 1$.

- $\mathbf{b}$ is a vector of length $p$ that contains the OLS estimate of the regression coefficients.

The formula calculates the OLS estimate of the regression coefficients by first finding the inverse of the matrix $\mathbf{X}^T \mathbf{X}$, then multiplying it by the matrix $\mathbf{X}^T \mathbf{y}$. The resulting vector $\mathbf{b}$ contains the OLS estimate of the regression coefficients that minimizes the sum of squared residuals between the predicted values and the actual values of the response variable $\mathbf{y}$.

In [1]:
import numpy as np

In [2]:
class MultipleLinearRegression:
    def __init__(self):
        self.coefficients_ = None
        self.intercept_ = None
        self.residuals_ = None
        self.RSS = None
        self.TSS = None
        self.r2score_ = None
        self.MAE = None
        self.MSE = None
        self.RMSE = None
        
    def fit(self, X, y):
        n, p = X.shape[0], X.shape[1]
        
        # Add a column of ones to the X matrix for the intercept_ 
        ones = np.ones((n, 1))
        X = np.hstack((ones, X))
        
        # Calculate the coefficients (b1, b2, ... bp) and intercept (bo)
        X_transpose = np.transpose(X)
        X_transpose_X = np.dot(X_transpose, X)
        X_transpose_X_inv = np.linalg.inv(X_transpose_X)
        X_transpose_X_inv_X_transpose = np.dot(X_transpose_X_inv, X_transpose)
        self.coefficients_ = np.dot(X_transpose_X_inv_X_transpose, y)
        self.intercept_ = self.coefficients_[0]
        
        # Calculate the predicted values and residuals
        y_pred = np.dot(X, self.coefficients_)
        self.residuals_ = y - y_pred
        
        # Calculate the residual sum of squares (RSS) anf total sum of squares (TSS) 
        self.RSS = np.sum(self.residuals_ ** 2)
        self.TSS = np.sum((y - np.mean(y)) ** 2)   
        
        # Calculate the coefficient of determination (R-squared)
        self.r2score_ = 1 - (self.RSS / self.TSS)
        
        # Calculate the mean absolute error (MAE)
        self.MAE = np.mean(np.abs(self.residuals_))

        # Calculate the mean squared error (MSE)
        self.MSE = np.mean(self.residuals_ ** 2)

        # Calculate the root mean squared error (RMSE)
        self.RMSE = np.sqrt(self.MSE)
        
    def predict(self, X):
        ones = np.ones((X.shape[0], 1))
        X = np.hstack((ones, X))
        return np.dot(X, self.coefficients_)

In [3]:
# Create a dictionary with column names as keys and lists as values
d = {'c1': [1, 2, 4, 3, 5], 'c2': [1, 3, 3, 2, 5], 'c3': [3, 7, 9, 5, 11]}

In [4]:
import pandas as pd

In [5]:
# Create the DataFrame
df = pd.DataFrame(data=d)

In [6]:
df

c1  c2  c3
0   1   1   3
1   2   3   7
2   4   3   9
3   3   2   5
4   5   5  11

In [7]:
X = df.iloc[:, :-1].values    # inputs or features or independent variables or predictor variables
y = df.iloc[:, -1].values     # output or target or dependent variable or response variable

In [8]:
print(type(X))
print(X.ndim)
print(X.shape)

print(type(y))
print(y.ndim)
print(y.shape)

<class 'numpy.ndarray'>
2
(5, 2)
<class 'numpy.ndarray'>
1
(5,)


In [9]:
X

array([[1, 1],
       [2, 3],
       [4, 3],
       [3, 2],
       [5, 5]], dtype=int64)

In [10]:
y

array([ 3,  7,  9,  5, 11], dtype=int64)

In [11]:
# Create an instance of the MultipleLinearRegression class
model = MultipleLinearRegression()

# Fit the model to the data
model.fit(X, y)

# Predict the model to the data
pred = model.predict(X)

In [12]:
# Print the multiple linear equation, coefficients, and intercept
print(f"Multilinear equation: y = {model.coefficients_[0]:.2f} + {model.coefficients_[1]:.2f}x1 + {model.coefficients_[2]:.2f}x2")
print(f"Coefficients: {model.coefficients_[1:]}")
print(f"Intercept: {model.intercept_:.2f}")

# Print the residuals, total sum of squares, residual sum of squares, and R-squared
print(f"Residuals: {model.residuals_}")
print(f"Total sum of squares (TSS): {model.TSS:.2f}")
print(f"Residual sum of squares (RSS): {model.RSS:.2f}")
print(f"Coefficient of determination (R^2): {model.r2score_:.2f}")

# Print the (MAE), (MSE), and (RMSE)
print(f"Mean Absolute Error (MAE): {model.MAE:.2f}")
print(f"Mean Squared Error (MSE): {model.MSE:.2f}")
print(f"Root Mean Squared Error (RMSE): {model.RMSE:.2f}")

Multilinear equation: y = 1.00 + 0.60x1 + 1.50x2
Coefficients: [0.6 1.5]
Intercept: 1.00
Residuals: [-0.1  0.3  1.1 -0.8 -0.5]
Total sum of squares (TSS): 40.00
Residual sum of squares (RSS): 2.20
Coefficient of determination (R^2): 0.95
Mean Absolute Error (MAE): 0.56
Mean Squared Error (MSE): 0.44
Root Mean Squared Error (RMSE): 0.66


In [13]:
y

array([ 3,  7,  9,  5, 11], dtype=int64)

$ \hat{y} = b_0 + b_1 x_1 + b_2 x_2 + \cdots + b_p x_p$

In [14]:
pred

array([ 3.1,  6.7,  7.9,  5.8, 11.5])

#### Train Test Split

Split the dataset into training and testing sets.

Parameters:
- X (numpy.ndarray): Array of features.
- y (numpy.ndarray): Array of target values.
- test_size (float): Fraction of the data to use for testing (default=0.33).
- random_state (int): Seed for the random number generator (default=None).

Returns:
- Tuple of X_train, X_test, y_train, y_test arrays.

In [15]:
def train_test_split_np(X, y, test_size=0.33, random_state=None):
    if random_state:
        np.random.seed(random_state)
    
    # Get the number of samples in the dataset
    n_samples = X.shape[0]

    # Shuffle the indices of the samples
    indices = np.random.permutation(n_samples)

    # Calculate the number of samples in the training and testing sets
    n_train_samples = int((1 - test_size) * n_samples)
    n_test_samples = n_samples - n_train_samples

    # Split the dataset into training and testing sets
    X_train = X[indices[:n_train_samples]]
    X_test = X[indices[n_train_samples:]]
    y_train = y[indices[:n_train_samples]]
    y_test = y[indices[n_train_samples:]]

    return X_train, X_test, y_train, y_test

In [16]:
# Sample data
X = np.array([[1, 1], [2, 3], [4, 3], [3, 2], [5, 5]])
y = np.array([3, 7, 9, 5, 11])

In [17]:
X

array([[1, 1],
       [2, 3],
       [4, 3],
       [3, 2],
       [5, 5]])

In [18]:
y

array([ 3,  7,  9,  5, 11])

In [19]:
X_train, X_test, y_train, y_test = train_test_split_np(X, y, test_size=0.33, random_state=42)

In [20]:
X_train

array([[2, 3],
       [5, 5],
       [4, 3]])

In [21]:
y_train

array([ 7, 11,  9])

In [22]:
X_test

array([[1, 1],
       [3, 2]])

In [23]:
y_test

array([3, 5])

## Python + NumPy 

In [24]:
import numpy as np

In [25]:
class MultipleLinearRegression:
    def __init__(self):
        self.coef_ = None
        self.intercept_ = None
        
    def fit(self, X, y):
        # Add a column of ones to the X matrix for the intercept_ 
        ones = np.ones((X.shape[0], 1))
        X = np.hstack((ones, X))
        
        # Calculate the coefficients (b1, b2, ... bp) and intercept (bo)
        X_transpose = np.transpose(X)
        X_transpose_X = np.dot(X_transpose, X)
        X_transpose_X_inv = np.linalg.inv(X_transpose_X)
        X_transpose_X_inv_X_transpose = np.dot(X_transpose_X_inv, X_transpose)
        self.coef_ = np.dot(X_transpose_X_inv_X_transpose, y)
        self.intercept_ = self.coef_[0]
        
    def predict(self, X):
        ones = np.ones((X.shape[0], 1))
        X = np.hstack((ones, X))
        return np.dot(X, self.coef_)
    
    def score(self, X, y):
        ones = np.ones((X.shape[0], 1))
        X = np.hstack((ones, X))
        y_pred = np.dot(X, self.coef_)
        residuals = y - y_pred
        RSS = np.sum(residuals ** 2)
        TSS = np.sum((y - np.mean(y)) ** 2)
        r2score = 1 - (RSS / TSS)
        return r2score

In [26]:
def train_test_split(X, y, test_size=0.33, random_state=None):
    # Set random seed if specified
    if random_state:
        np.random.seed(random_state)
    
    # Shuffle data and split into training and testing sets
    indices = np.random.permutation(X.shape[0])
    split_index = int(X.shape[0] * (1 - test_size))
    X_train, X_test = X[indices[:split_index]], X[indices[split_index:]]
    y_train, y_test = y[indices[:split_index]], y[indices[split_index:]]

    return X_train, X_test, y_train, y_test

In [27]:
class Metrics:
    @staticmethod
    def r2_score(y_true, y_pred):
        SST = np.sum((y_true - np.mean(y_true)) ** 2)
        RSS = np.sum((y_true - y_pred) ** 2)
        return 1 - (RSS / SST)

    @staticmethod
    def mean_absolute_error(y_true, y_pred):
        return np.mean(np.abs(y_true - y_pred))

    @staticmethod
    def mean_squared_error(y_true, y_pred):
        return np.mean((y_true - y_pred) ** 2)
    
    @staticmethod
    def root_mean_squared_error(y_true, y_pred):
        mse = np.mean((y_true - y_pred) ** 2)
        rmse = np.sqrt(mse)
        return rmse

In [28]:
# Generate some sample data
np.random.seed(42)
n = 100
p = 3
X = np.random.randn(n, p)
y = 2*X[:,0] + 3*X[:,1] - 1*X[:,2] + np.random.randn(n)

In [29]:
import pandas as pd

In [30]:
data = pd.concat([pd.DataFrame(X, columns=['X1', 'X2', 'X3']), pd.DataFrame(y, columns=['y'])], axis=1, )
data.to_csv('data.csv', index=False)

In [31]:
data.head()

X1        X2        X3         y
0  0.496714 -0.138264  0.647689 -0.898048
1  1.523030 -0.234153 -0.234137  2.017556
2  1.579213  0.767435 -0.469474  6.677498
3  0.542560 -0.463418 -0.465730  0.770967
4  0.241962 -1.913280 -1.724918 -3.551900

In [32]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [33]:
model = MultipleLinearRegression()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)  

In [34]:
print(f"Coefficient of determination (R^2): {model.score(X_test, y_test):.2f}")

Coefficient of determination (R^2): 0.92


In [35]:
print(f"Coefficient of determination (R^2): {Metrics.r2_score(y_test, y_pred):.2f}")
print(f"Mean Absolute Error (MAE): {Metrics.mean_absolute_error(y_test, y_pred):.2f}")
print(f"Mean Squared Error (MSE): {Metrics.mean_squared_error(y_test, y_pred):.2f}")
print(f"Root Mean Squared Error (RMSE): {Metrics.root_mean_squared_error(y_test, y_pred):.2f}")

Coefficient of determination (R^2): 0.92
Mean Absolute Error (MAE): 0.83
Mean Squared Error (MSE): 1.08
Root Mean Squared Error (RMSE): 1.04


In [36]:
print(f"Multiple linear equation: y = {model.intercept_:.4f} + {model.coef_[1]:.4f}x1 + {model.coef_[2]:.4f}x2 + {model.coef_[3]:.4f}x3")
print(f"Slope: {model.coef_[1:]}")
print(f"Intercept: {model.intercept_:.4f}")

Multiple linear equation: y = 0.0120 + 1.9183x1 + 3.0357x2 + -1.1099x3
Slope: [ 1.91831705  3.03573198 -1.10988093]
Intercept: 0.0120


## Scikit-Learn

In [37]:
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split

from sklearn.linear_model import LinearRegression

from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error

In [38]:
df = pd.read_csv('data.csv')

In [39]:
X = df.iloc[:, :-1].values
y = df.iloc[:, -1].values 

In [40]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [41]:
model = LinearRegression()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)

In [42]:
print(f"Coefficient of determination (R^2): {model.score(X_test, y_test):.2f}")

Coefficient of determination (R^2): 0.94


In [43]:
print(f"Coefficient of determination (R^2): {r2_score(y_test, y_pred):.2f}")
print(f"Mean Absolute Error (MAE): {mean_absolute_error(y_test, y_pred):.2f}")
print(f"Mean Squared Error (MSE): {mean_squared_error(y_test, y_pred):.2f}")
print(f"Root Mean Squared Error (RMSE): {np.sqrt(mean_squared_error(y_test, y_pred)):.2f}")

Coefficient of determination (R^2): 0.94
Mean Absolute Error (MAE): 0.72
Mean Squared Error (MSE): 0.76
Root Mean Squared Error (RMSE): 0.87


In [44]:
print(f"Multilinear equation: y = {model.intercept_:.4f} + {model.coef_[0]:.4f}x1 + {model.coef_[1]:.4f}x2 + {model.coef_[2]:.4f}x3")
print(f"Slope: {model.coef_}")
print(f"Intercept: {model.intercept_:.4f}")

Multilinear equation: y = 0.2014 + 2.0314x1 + 2.9009x2 + -1.0094x3
Slope: [ 2.0314386   2.90090856 -1.00939987]
Intercept: 0.2014


## Statsmodels

In [45]:
import pandas as pd
import statsmodels.api as sm

from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score

In [46]:
df = pd.read_csv('data.csv')

In [47]:
X = df.iloc[:, :-1].values
y = df.iloc[:, -1].values 

In [48]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [49]:
X_train = sm.add_constant(X_train)
X_test = sm.add_constant(X_test)

In [50]:
model = sm.OLS(y_train, X_train).fit()
y_pred = model.predict(X_test)

In [51]:
print("R-squared:", model.rsquared)

R-squared: 0.9445253068209857


In [52]:
print(f"Coefficient of determination (R^2): {r2_score(y_test, y_pred):.2f}")

Coefficient of determination (R^2): 0.94


In [53]:
model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.945
Model:                            OLS   Adj. R-squared:                  0.942
Method:                 Least Squares   F-statistic:                     357.6
Date:                Sat, 25 Feb 2023   Prob (F-statistic):           1.71e-39
Time:                        12:48:27   Log-Likelihood:                -87.947
No. Observations:                  67   AIC:                             183.9
Df Residuals:                      63   BIC:                             192.7
Df Model:                           3                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          0.2014      0.118      1.707      0.093      -0.034       0.437
x1             2.0314      0.137     14.813      0.000       1.757       2.305
x2             2.9009      0.131     22.219      0.000       2.640       3.162
x3            -1.0094      0.111     -9.086      0.000      -1.231      -0.787
==============================================================================
Omnibus:                        0.036   Durbin-Watson:                   1.811
Prob(Omnibus):                  0.982   Jarque-Bera (JB):                0.066
Skew:                           0.040   Prob(JB):                        0.967
Kurtosis:                       2.869   Cond. No.                         1.54
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

## NumPy

In [54]:
import numpy as np

In [55]:
class MultipleLinearRegression:
    def __init__(self):
        self.coef_ = None
        self.intercept_ = None
        
    def fit(self, X, y):
        # Add a column of ones to X for the intercept
        X = np.c_[np.ones(X.shape[0]), X]   
        
        # Compute coefficients and set intercept to first coefficient
        self.coef_ = np.linalg.inv(X.T @ X) @ X.T @ y  
        self.intercept_ = self.coef_[0]  
        
    def predict(self, X):
        # Add a column of ones to X for the intercept
        X = np.c_[np.ones(X.shape[0]), X]  
        return X @ self.coef_
    
    def score(self, X, y):
        y_pred = self.predict(X)
        RSS = np.sum((y - y_pred) ** 2)
        TSS = np.sum((y - np.mean(y)) ** 2)
        r2score = 1 - (RSS / TSS)
        return r2score

## PyTorch 

In [56]:
import torch

In [57]:
class MultipleLinearRegression:
    def __init__(self):
        self.coef_ = None
        self.intercept_ = None
        
    def fit(self, X, y):
        # Add a column of ones to X for the intercept
        ones = torch.ones((X.shape[0], 1), dtype=torch.float32)
        X = torch.cat((ones, X), dim=1)
        
        # Compute coefficients and set intercept to first coefficient
        X_t = torch.transpose(X, 0, 1)
        self.coef_ = torch.inverse(X_t @ X) @ X_t @ y
        self.intercept_ = self.coef_[0]
        
    def predict(self, X):
        # Add a column of ones to X for the intercept
        ones = torch.ones((X.shape[0], 1), dtype=torch.float32)
        X = torch.cat((ones, X), dim=1)
        return X @ self.coef_
    
    def score(self, X, y):
        y_pred = self.predict(X)
        RSS = torch.sum((y - y_pred) ** 2)
        TSS = torch.sum((y - torch.mean(y)) ** 2)
        r2score = 1 - (RSS / TSS)
        return r2score.numpy()

## Data Transformations  

<b>Preprocessing for Machine Learning (Prepping Data for Modelling)</b>

Transforming Numeric Data (Feature Scaling)
- Linear Scaling / Min-Max Normalization / Normalization
- Z-score / Standard Score / Z-score Normalization / Standardization

Transforming Categorical Data 
- Label Encoding 
- OneHot Encoding 

In [58]:
import numpy as np

In [59]:
class StandardScaler:
    def __init__(self):
        self.mean_ = None
        self.std_ = None
        
    def fit(self, X):
        self.mean_ = np.mean(X, axis=0)
        self.std_ = np.std(X, axis=0)
        
    def transform(self, X):
        return (X - self.mean_) / self.std_
    
class MinMaxScaler:
    def __init__(self):
        self.min_ = None
        self.max_ = None
        
    def fit(self, X):
        self.min_ = np.min(X, axis=0)
        self.max_ = np.max(X, axis=0)
        
    def transform(self, X):
        return (X - self.min_) / (self.max_ - self.min_)
    
class LabelEncoder:
    def __init__(self):
        self.categories_ = None
        
    def fit(self, X):
        self.categories_ = np.unique(X)
        
    def transform(self, X):
        if self.categories_ is None:
            raise ValueError("Call fit method first")
        
        X_encoded = np.zeros(len(X), dtype=int)
        for i, category in enumerate(self.categories_):
            X_encoded[X == category] = i
            
        return X_encoded
    
class OneHotEncoder:
    def __init__(self):
        self.categories_ = None
        self.num_categories_ = None
        
    def fit(self, X):
        self.categories_ = np.unique(X)
        self.num_categories_ = len(self.categories_)
        
    def transform(self, X):
        if self.num_categories_ is None:
            raise ValueError("Call fit method first")
        
        X_encoded = np.zeros((len(X), self.num_categories_))
        for i, category in enumerate(self.categories_):
            X_encoded[:, i] = (X == category)
            
        return X_encoded

## Summary 

<b>Linear Regression</b> (SLR or MLR or PLR) is a popular technique for modeling the relationship between a dependent variable and one or more independent variables. There are several methods to implement linear regression.

- <b>Ordinary Least Squares (OLS)</b>: OLS is a classic method that minimizes the sum of squared residuals between the observed and predicted values of the dependent variable. OLS assumes that the residuals are normally distributed and have constant variance.

$$y = b_0 + b_1 x$$

$$y = b_0 + b_1 x_1 + b_2 x_2 + \cdots + b_n x_n$$

$$y = b_0 + b_1 x + b_2 x^2 + b_3 x^3 + \cdots + b_n x^n$$

- <b>Ridge Regression</b>: Ridge regression is a variant of linear regression that includes a penalty term for large parameter values. The penalty term is controlled by a hyperparameter, which is chosen using cross-validation. Ridge regression can help to reduce overfitting in the model.

$$y = b_0 + b_1x_1 + b_2x_2 + ... + b_nx_n + \lambda(b_1^2 + b_2^2 + ... + b_n^2)$$

$$y = b_0 + b_1x_1 + b_2x_2 + ... + b_nx_n + \lambda\sum_{i=1}^{n}b_i^2$$

$$y = b_0 + \sum_{i=1}^{n} b_i x_i + \lambda \sum_{i=1}^{n} b_i^2$$

- <b>Lasso Regression</b>: Lasso regression is another variant of linear regression that includes a penalty term, but uses the absolute value of the parameter values instead of the squared values. Lasso regression can be used for feature selection, as it tends to set the coefficients of irrelevant features to zero.

$$y = b_0 + \sum_{i=1}^{n} b_i x_i + \lambda \sum_{i=1}^{n} |b_i|$$

- <b>Elastic Net Regression</b>: Elastic net regression is a combination of ridge and lasso regression, which includes both L1 and L2 penalty terms. Elastic net regression can be used to balance the bias-variance tradeoff and can be particularly useful when there are many correlated features.

$$y = b_0 + \sum_{i=1}^{n} b_i x_i + \lambda_1 \sum_{i=1}^{n} |b_i| + \lambda_2 \sum_{i=1}^{n} b_i^2$$

- <b>Bayesian Linear Regression</b>: Bayesian linear regression is a method that uses Bayesian statistics to estimate the parameters of the regression model. It involves specifying prior distributions over the parameters and using Bayes' theorem to update the priors based on the observed data.

- <b>Gradient Descent</b>: Gradient descent is an iterative optimization algorithm that minimizes the cost function (the sum of squared residuals) by updating the model parameters in the direction of the negative gradient of the cost function.
    - Batch Gradient Descent (BGD)
    - Stochastic Gradient Descent (SGD)
    - Mini-Batch Gradient Descent (MBGD)
    - Momentum-based Gradient Descent
    - Adagrad
    - Adam

@rizwan-ai

## Happy Learning :)